config/routes.rb
Rails.application.routes.draw do
  # get 'bike/show'

  # get 'bike/new'

  # get 'bike/create'

  # get 'bike/edit'

  # get 'bike/update'

  # get 'bike/delete'

  # get 'bike/destroy'

  resources :bike

  # get 'user/index'

  # get 'user/create'

  # get 'user/edit'

  # get 'user/update'

  # get 'user/new'

  # get 'user/destroy'

  # get 'user/show'

  root 'home#index'

  resources :user

  get "login" => "sessions#new"

  post "login" => "sessions#create"
  
  get "logout" => "sessions#destroy"

  get "about" => "home#about"

  get "zoe" => "home#zoe"

  get 'results' => "bike#results"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user

  def self.search(search)
    where("brand || 
          model || 
          description ||
          color_primary ||
          color_secondary ||
          color_tertiary ILIKE ?", "%#{search}%")

  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :bikes

  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false}

  has_secure_password

  validates :password,
  length: { in: 8..72 },
  on: :create

  def self.authenticate(params)
    User.find_by_email(params[:email]).try(:authenticate, params[:password])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_user

  def is_authenticated
    unless current_user
      flash[:danger] = "Credentials Invalid!!"
      redirect_to login_path
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/controllers/bike_controller.rb
class BikeController < ApplicationController
  # require the gems we need
  require 'rest-client'
  require 'nokogiri'

  before_action :current_user, :is_authenticated

  def show
     @bike = Bike.find(params[:id])
    #request data
    response = RestClient.get("https://seattle.craigslist.org/search/bia")
    html = response.body
    #give Nokogiri your file
    data = Nokogiri::HTML(html)
    ##select data using CSS selectors
    titleArr = []
    linkArr = []
    data.css("a.hdrlnk:contains('#{@bike.brand}')", "a.hdrlnk:contains('#{@bike.model}')", "a.hdrlnk:contains('#{@bike.color_primary}')").each do |title|
      titleArr = titleArr.push(title.text)
      @titles = titleArr

      linkArr = linkArr.push(title.attr('href'))
      @links = linkArr
    end
  end

  def new
    @bike = Bike.new
  end

  def index
    @users = User.all

  end

  def create
    uploaded_bike_photo = bike_params[:photo].path
    cloudinary_file = Cloudinary::Uploader.upload(uploaded_bike_photo)
    new_bike = {
        :user_id            => bike_params[:user_id],
        :description        => bike_params[:description],
        :brand              => bike_params[:brand],
        :model              => bike_params[:model],
        :color_primary      => bike_params[:color_primary],
        :color_secondary    => bike_params[:color_secondary],
        :color_tertiary     => bike_params[:color_tertiary],
        :serial_num         => bike_params[:serial_num],
        :is_stolen          => bike_params[:is_stolen],
        :stolen_zip         => bike_params[:stolen_zip],
        :stolen_date        => bike_params[:stolen_date],
        :photo              => cloudinary_file['public_id'],
        :frame_size         => bike_params[:frame_size]
    }
    Bike.create(new_bike)
    redirect_to root_path
  end

  def edit
    @bike = Bike.find(params[:id])
  end

  def update
    b = Bike.find(params[:id])
    b.update(bike_params)
    redirect_to root_path
  end

  def delete
  end


  def destroy
    Bike.find(params[:id]).delete
    redirect_to root_path

  end

  def results
    query = params[:search]
    if query
      @bikes = Bike.search(query)
    else
      @bikes = Bike.all
    end
  end




  private

  def bike_params
    defaults = { user_id: current_user.id }
    params.require(:bike).permit(:user_id,
                                :description,
                                :brand,
                                :model,
                                :color_primary,
                                :color_secondary,
                                :color_tertiary,
                                :serial_num,
                                :is_stolen,
                                :stolen_zip,
                                :stolen_date,
                                :photo,
                                :frame_size).reverse_merge(defaults)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def zoe
    render "zoe"
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(user_params)

    if user
      session[:user_id] = user.id
      flash[:success] = "#{user.name} logged in!!"
      redirect_to root_path
    else
      flash[:danger] = "Credentials Invalid!!"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "User logged out!!"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def create
    User.create(user_params)
    redirect_to root_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    u = User.find(params[:id])
    u.update(user_params)
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def destroy
  end

  def show
    @user = User.find(params[:id])
    @bikes = @user.bikes
  end

  def user_params
   params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bike_helper.rb
module BikeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/bike/create.html.erb
<h1>Bike#create</h1>
<p>Find me in app/views/bike/create.html.erb</p>

app/views/bike/delete.html.erb
<h1>Bike#delete</h1>
<p>Find me in app/views/bike/delete.html.erb</p>

app/views/bike/destroy.html.erb
<h1>Bike#destroy</h1>
<p>Find me in app/views/bike/destroy.html.erb</p>

app/views/bike/edit.html.erb
<div class="bikeForm container">

    <%= form_for @bike do |form| %>

    <div class="page-heading mui--text-light mui--text-display1" style="text-align: center;">Edit a bike</div>

    <div class="form-section panel container">
        <h3>Information</h3>
        <div class="row">
            <div class="col-md-6">
                <div class="mui-textfield ">
                    <%= form.label :brand %>
                    <%= form.text_field :brand %>
                </div>
            </div>

            <div class="col-md-6">
                <div class="mui-textfield">
                    <%= form.label :model %>
                    <%= form.text_field :model %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.text_field :serial_num %>
                    <%= form.label :serial_number %>
                </div>
            </div>
        </div>
    </div>

    <div class="form-section panel container">
        <h3>Appearance</h3>

        <div class="row">
            <div class="col-md-4">
                <div class="mui-select">
                    <%= form.label :Primary_color %>
                    <%= form.select :color_primary, [
                    ['None', 'none'],
                    ['Red','red'],
                    ['Dark Red', 'dark red'],
                    ['Light Red', 'light red'],
                    ['Blue','blue'],
                    ['Dark Blue','dark blue'],
                    ['Light Blue','light blue'],
                    ['Green','green'],
                    ['Dark Green','dark green'],
                    ['Light Green','light green'],
                    ['Yellow','yellow'],
                    ['Orange','orange'],
                    ['White','white'],
                    ['Black', 'black'],
                    ['Grey','grey'],
                    ['Purple','purple']] %>
                </div>
            </div>

            <div class="col-md-4">
                <div class="mui-select">
                    <%= form.label :Secondary_color %>
                    <%= form.select :color_secondary, [
                    ['None', 'none'],
                    ['Red','red'],
                    ['Dark Red', 'dark red'],
                    ['Light Red', 'light red'],
                    ['Blue','blue'],
                    ['Dark Blue','dark blue'],
                    ['Light Blue','light blue'],
                    ['Green','green'],
                    ['Dark Green','dark green'],
                    ['Light Green','light green'],
                    ['Yellow','yellow'],
                    ['Orange','orange'],
                    ['White','white'],
                    ['Black', 'black'],
                    ['Grey','grey'],
                    ['Purple','purple']] %>
                </div>
            </div>

            <div class="col-md-4">
                <div class="mui-select">
                    <%= form.label :Tertiary_color %>
                    <%= form.select :color_tertiary, [
                    ['None', 'none'],
                    ['Red','red'],
                    ['Dark Red', 'dark red'],
                    ['Light Red', 'light red'],
                    ['Blue','blue'],
                    ['Dark Blue','dark blue'],
                    ['Light Blue','light blue'],
                    ['Green','green'],
                    ['Dark Green','dark green'],
                    ['Light Green','light green'],
                    ['Yellow','yellow'],
                    ['Orange','orange'],
                    ['White','white'],
                    ['Black', 'black'],
                    ['Grey','grey'],
                    ['Purple','purple']] %>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.text_area :description, class: '', id: 'description', placeholder: 'Has a Georgetown
                    Brewing Company sticker on downtube, scratch on front fork, pink tassles on handlebars. Was locked
                    up at 3rd and University bike rack when Kryptonite U-lock was snipped between 1pm and 3pm.' %>
                    <%= form.label :description, class: '', for: 'description' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.label :photo %>
                    <%= form.file_field :photo, class: 'mui-btn' %>
                </div>
            </div>
        </div>
    </div>
    <div class="form-section panel container">
        <h3>Missing Status</h3>

        <div class="row" id="stolen-section">
            <div class="col-md-6" style="padding-left: 70px;">
                <div class="mui-textfield">
                    <div class="row mui-radio"
                         style="position: absolute; top: 0; display: block; width: 100%; color: rgba(0,0,0,.54); font-size: 12px; font-weight: 400; line-height: 15px; overflow-x: hidden; text-overflow: ellipsis; white-space: nowrap;">
                        <%= form.radio_button(:is_stolen, true, {:class => "true_clicked" }) %>
                        <%= form.label(:bike_true, "My bike was stolen") %>
                    </div>
                    <div class="row mui-radio"
                         style="position: absolute; top: 0; display: block; width: 100%; color: rgba(0,0,0,.54); font-size: 12px; font-weight: 400; line-height: 15px; overflow-x: hidden; text-overflow: ellipsis; white-space: nowrap;">
                        <%= form.radio_button(:is_stolen, false, {:class => "false_clicked"}) %>
                        <%= form.label(:bike_false, "My bike was not stolen", class: '', for: 'is_stolen') %>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="stolen_form" style="display: none">

                    <div class="row">
                        <div class="mui-textfield">
                            <%= form.text_field :stolen_zip, class: '', id: 'stolen_zip' %>
                            <%= form.label :stolen_zip %>
                        </div>
                    </div>

                    <div class="row">
                        <div class="mui-textfield">
                            <%= form.text_field :stolen_date, class: '', id: 'stolen_date', placeholder: '01/01/16' %>
                            <%= form.label :stolen_date %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="text-align: center; padding-top: 50px;">
        <%= form.submit 'Save', :class => 'mui-btn mui-btn--primary' %>
    </div>

    <%end%>

</div>

app/views/bike/index.html.erb
<div class="bikeForm container">

    <%= form_for :bike do |form| %>

    <div class="page-heading mui--text-light mui--text-display1" style="text-align: center;">Add a bike</div>

    <div class="form-section panel container">
        <h3>Information</h3>

        <div class="row">
            <div class="col-md-6">
                <div class="mui-textfield">
                    <%= form.text_field :brand, class: '', id: 'brand' %>
                    <%= form.label :brand, class: '', for: 'brand' %>
                </div>
            </div>

            <div class="col-md-6">
                <div class="mui-textfield">
                    <%= form.text_field :model, class: '', id: 'model' %>
                    <%= form.label :model, class: '', for: 'model' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.text_field :serial_num, class: '', id: 'serial_num' %>
                    <%= form.label :serial_number, class: '', for: 'serial_num' %>
                </div>
            </div>
        </div>
    </div>

    <div class="form-section panel container">
        <h3>Appearance</h3>

        <div class="row">
            <div class="col-md-4">
                <div class="mui-select">
                    <%= form.label :Primary_color %>
                    <%= form.select :color_primary, [
                    ['None', 'none'],
                    ['Red','red'],
                    ['Dark Red', 'dark red'],
                    ['Light Red', 'light red'],
                    ['Blue','blue'],
                    ['Dark Blue','dark blue'],
                    ['Light Blue','light blue'],
                    ['Green','green'],
                    ['Dark Green','dark green'],
                    ['Light Green','light green'],
                    ['Yellow','yellow'],
                    ['Orange','orange'],
                    ['White','white'],
                    ['Black', 'black'],
                    ['Grey','grey'],
                    ['Purple','purple']] %>
                </div>
            </div>

            <div class="col-md-4">
                <div class="mui-select">
                    <%= form.label :Secondary_color %>
                    <%= form.select :color_secondary, [
                    ['None', 'none'],
                    ['Red','red'],
                    ['Dark Red', 'dark red'],
                    ['Light Red', 'light red'],
                    ['Blue','blue'],
                    ['Dark Blue','dark blue'],
                    ['Light Blue','light blue'],
                    ['Green','green'],
                    ['Dark Green','dark green'],
                    ['Light Green','light green'],
                    ['Yellow','yellow'],
                    ['Orange','orange'],
                    ['White','white'],
                    ['Black', 'black'],
                    ['Grey','grey'],
                    ['Purple','purple']] %>
                </div>
            </div>

            <div class="col-md-4">
                <div class="mui-select">
                    <%= form.label :Tertiary_color %>
                    <%= form.select :color_tertiary, [
                    ['None', 'none'],
                    ['Red','red'],
                    ['Dark Red', 'dark red'],
                    ['Light Red', 'light red'],
                    ['Blue','blue'],
                    ['Dark Blue','dark blue'],
                    ['Light Blue','light blue'],
                    ['Green','green'],
                    ['Dark Green','dark green'],
                    ['Light Green','light green'],
                    ['Yellow','yellow'],
                    ['Orange','orange'],
                    ['White','white'],
                    ['Black', 'black'],
                    ['Grey','grey'],
                    ['Purple','purple']] %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.text_area :description, class: '', id: 'description' %>
                    <%= form.label :description_and_cosmetic_details, class: '', for: 'description' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="mui-textfield">
                    <%= form.label :photo %>
                    <%= form.file_field :photo, class: 'mui-btn' %>
                </div>
            </div>
        </div>
    </div>

    <div class="form-section panel container">
        <h3>Missing Status</h3>

        <div class="row" id="stolen-section">
            <div class="col-md-6" style="padding-left: 70px;">
                <div class="mui-textfield">
                    <div class="row mui-radio"
                         style="position: absolute; top: 0; display: block; width: 100%; color: rgba(0,0,0,.54); font-size: 12px; font-weight: 400; line-height: 15px; overflow-x: hidden; text-overflow: ellipsis; white-space: nowrap;">
                        <%= form.radio_button(:is_stolen, true, {:class => "true_clicked" }) %>
                        <%= form.label(:bike_true, "My bike was stolen") %>
                    </div>
                    <div class="row mui-radio"
                         style="position: absolute; top: 0; display: block; width: 100%; color: rgba(0,0,0,.54); font-size: 12px; font-weight: 400; line-height: 15px; overflow-x: hidden; text-overflow: ellipsis; white-space: nowrap;">
                        <%= form.radio_button(:is_stolen, false, {:class => "false_clicked"}) %>
                        <%= form.label(:bike_false, "My bike was not stolen", class: '', for: 'is_stolen') %>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="stolen_form" style="display: none">

                    <div class="row">
                        <div class="mui-textfield">
                            <%= form.text_field :stolen_zip, class: '', id: 'stolen_zip' %>
                            <%= form.label :stolen_zip %>
                        </div>
                    </div>

                    <div class="row">
                        <div class="mui-textfield">
                            <%= form.text_field :stolen_date, class: '', id: 'stolen_date', placeholder: '01/01/16' %>
                            <%= form.label :stolen_date %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="text-align: center; padding-top: 50px;">
        <%= form.submit 'Register', :class => 'mui-btn mui-btn--primary' %>
    </div>

    <%end%>


</div>

app/views/bike/new.html.erb
<h1>Bike#new</h1>
<p>Find me in app/views/bike/new.html.erb</p>

app/views/bike/results.html.erb
<div class='container'>

    <div class='col-md-1'></div>

    <div class='col-md-7 well' id='user-bikes'>

        <h3>Searched Bikes:</h3>

        <% @bikes.each do |bike| %>

        <div class="user-bikes">
            <div class="row">

                <div class="col-md-6">
                    <%= cl_image_tag(bike.photo, :width => 250, :class => 'img-thumbnail img-responsive') %>
                </div>

                <div class="col-md-6">
                    <h4><a href="/bike/<%= bike.id %>"><%= bike.serial_num %></a></h4>
                    <h6><label>Brand: </label> <%= bike.brand %></h6>
                    <h6><label>Model: </label> <%= bike.model %></h6>
                    <h6><label>Is Missing: </label> <%= bike.is_stolen %></h6>

                </div>
            </div>
        </div>

        <% end %>

    </div>

</div>

app/views/bike/show.html.erb
<div class='container'>

    <div class="row">
        <div class="col-md-4" id="bike-image">
            <%= cl_image_tag(@bike.photo, :width => 400, :class => 'img-thumbnail') %>
        </div>

        <div class="col-md-1"></div>

        <div class="col-md-7 panel" id="bike-info" style="text-align: left;">

            <h3>
                <label>Brand:</label>
                <%= @bike.brand %>
            </h3>

            <h3>
                <label>Model:</label>
                <%= @bike.model %>
            </h3>

            <h3>
                <label>Serial Number:</label>
                <%= @bike.serial_num %>
            </h3>

            <div class="row">
                <div class="col-md-6">
                    <label>Colors:</label>
                    <ul>
                        <li>Primary: <strong><span style="color: <%= @bike.color_primary %>"><%= @bike.color_primary %></span></strong>
                        </li>
                        <li>Secondary: <strong><span style="color: <%= @bike.color_secondary %>"><%= @bike.color_secondary %></span></strong>
                        </li>
                        <li>Tertiary: <strong><span style="color: <%= @bike.color_tertiary %>"><%= @bike.color_tertiary %></span></strong>
                        </li>
                    </ul>
                </div>

                <div class="col-md-6">
                    <label>Status:</label>
                    <ul>
                        <li>Missing: <%= @bike.is_stolen %></li>
                        <li>Last known location: <%= @bike.stolen_zip %></li>
                        <li>Last seen date: <%= @bike.stolen_date %></li>
                    </ul>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <label>Desciption and additional details:</label>
                    <p>
                        <%= @bike.description %>
                    </p>
                </div>
            </div>

            <hr>

            <div class="row" id="contact-owner">
                <a href="#">contact owner</a>
                |
                <a href="#">return</a>
            </div>
        </div>

    </div>
    <%if @bike.is_stolen == true%>
    <%= render "partials/sitewide_assets/craigslist" %>
    <%end%>


</div>

app/views/bike/update.html.erb
<h1>Bike#update</h1>
<p>Find me in app/views/bike/update.html.erb</p>

app/views/home/about.html.erb
<div class='container' id="about-page">

  <div class="row well">

    <div class='col-md-3'>
      <a href='zoe'>
        <div class='jumbotron' id='zoe-jumbotron'>
          <h2>Zoe</h2>
        </div>
      </a>
    </div>

  </div>

 </div>

app/views/home/index.html.erb
<div class="container">
  <h1 id="main-title">Accio Bike</h1>
</div>

<%= render "partials/home/bike" %>

<div class='container' id='frontpage-text'>
   <p>
       Bike theft happens far too often in Seattle.
   </p>
    <p>
        You'd be hard pressed to find someone who hasn't been affected by it.
   </p>
    <p>
        Accio Bike is named after the spell from "Harry Potter" that fetches and returns objects. Create a user profile and register your bikes. If your bike goes missing, update your bike's profile. Other users will be able to keep an eye out or return your bike if found. In addition, Accio Bike crawls Craigslist for bikes matching you listing in case your thief is trying to flip your bike for quick cash.
   </p>
</div>

app/views/home/zoe.html.erb
<div class='container'>
    <div class="row">
        <div class="col-md-4" id="about-profile-pic">
            <img src="http://res.cloudinary.com/dto1eenjq/image/upload/v1473372079/zoepic_cgmcdl.jpg"
                 class='img-thumbnail' height='400'>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-7 panel" id="about-bio">
            <h1 id='name'>
                ZOE MCDANIEL
            </h1>
            <div class="mui-divider" style="margin-top: 20px; margin-bottom: 20px;"></div>
            <div class="mui--text-body1">
                Zoe is the last living gigantosaurus and is sustained by the generous donations of the Bill Billerson Foundation. In 1492 she sailed the ocean blue. Although her lineage is doubted by some, she is the one true Zoe Regularborn of the House Ginger, the seventh of her name, Queen of the Sandals, the Chicken Nuggets and the First Sea Otters, Lady of the Seven Pillow Kingdoms and Protector of the Legos, the Sunburnt, Mother of Puppers, Breaker of Glasses, Queen of Cheese, Drinker of the Great Beanie Baby Sea.
            </div>
            <div class="mui-divider" style="margin-top: 20px; margin-bottom: 20px;"></div>
            <div id="about-social-links">
                <ul class="list-inline">
                    <li>
                        <div class="mui--text-dark-secondary mui--text-display2">
                            <a href="https://github.com/zmcdaniel">
                                <i class="fa fa-github" aria-hidden="true"></i>
                            </a>
                        </div>
                    </li>
                    <li>
                        <div class="mui--text-dark-secondary mui--text-display2">
                            <a href="https://www.linkedin.com/in/zoe-mcdaniel-7933bb66">
                                <i class="fa fa-linkedin" aria-hidden="true"></i>
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accio Bike!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render "partials/sitewide_assets/cssheader" %>
    <%= stylesheet_link_tag "bike.css", :media => 'screen' %>
  </head>

  <body>
    <%= render "partials/sitewide_assets/navbar" %>
    <%= render "partials/sitewide_assets/flash" %>

    <%= yield %>

    <%= render "partials/sitewide_assets/jslinks" %>
  </body>
</html>

app/views/partials/sitewide_assets/_craigslist.html.erb
<div class="col-md-5"></div>

<div class="col-md-7 panel" id="craigslist-info" style="text-align: left;">
    <%if @titles != nil%>
    <h4>Possible Craigslist matches</h4>
    <ul>
        <% 5.times do |i|%>
        <li><a href="https://seattle.craigslist.org<%=@links[i] %>"><%=@titles[i]%></a></li>
        <%end%>
    </ul>
    <%else%>
    <h3> No matches on craigslist :(</h3>
    <%end%>
</div>

app/views/partials/sitewide_assets/_cssheader.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Font for front page banner -->
<link href='http://fonts.googleapis.com/css?family=Amatic+SC:400,700' rel='stylesheet' type='text/css'>

<!-- Bootstrap latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- MUI Junk -->
<link href="//cdn.muicss.com/mui-0.7.5/css/mui.min.css" rel="stylesheet" type="text/css" />
<script src="//cdn.muicss.com/mui-0.7.5/js/mui.min.js"></script>

<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css">

<!-- Animation for bike and frontpage styles -->
<link rel="stylesheet" type="text/css" href="css/bike.css">

app/views/partials/sitewide_assets/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/user/edit.html.erb
<div class="container well">
    <h1>Edit your info</h1>

    <%= form_for @user do |form| %>

        <div class="md-form">
            <%= form.text_field :name, class: 'form-control', id: 'name' %>
            <%= form.label :name, class: '', for: 'name' %>
        </div>

        <div class="md-form">
            <%= form.text_field :email, class: 'form-control', id: 'email' %>
            <%= form.label :email, class: '', for: 'email' %>
        </div>

        <div class="md-form">
            <%= form.submit 'SUBMIT', :class => 'btn btn-primary' %>
        </div>

    <%end%>
</div>

app/views/user/show.html.erb
<div class='container'>

    <div class='col-md-3 well' id='user-info'>

        <h3>Hello, <%= @user.name %></h3>
        <label>Email: </label> <%= @user.email %>

        <hr>

        <a class="mui-btn mui-btn--primary mui-btn--small" href='/user/<%=@current_user.id%>/edit'>Edit Info</a>
        <a class="mui-btn mui-btn--primary mui-btn--small" href='/logout'>Log Out</a>
    </div>

    <div class='col-md-1'></div>

    <div class='col-md-7 well' id='user-bikes'>

        <h3>Your registered bikes:</h3>

        <% @bikes.each do |bike| %>

        <div class="mui-panel user-bikes">
            <div class="row">

                <div class="col-md-6">
                    <%= cl_image_tag(bike.photo, :width => 250, :class => 'img-thumbnail img-responsive') %>
                </div>

                <div class="col-md-6">
                    <h4><a href="/bike/<%= bike.id %>"><%= bike.serial_num %></a></h4>
                    <h6><label>Brand: </label> <%= bike.brand %></h6>
                    <h6><label>Model: </label> <%= bike.model %></h6>
                    <h6><label>Is Missing: </label> <%= bike.is_stolen %></h6>


                    <a class="mui-btn mui-btn--primary mui-btn--flat mui-btn--small" href='/bike/<%= bike.id %>/edit'>Edit</a>
                    <%= link_to "Delete Bike", bike_path(bike), method: :delete, class: 'mui-btn mui-btn--danger mui-btn--flat mui-btn--small' %>
                </div>
            </div>
        </div>

        <% end %>

    </div>

</div>